# Generated by Django 2.1.2 on 2018-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('category', models.CharField(max_length=255, verbose_name='Categoria')),
                ('preciseDate', models.DateField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
