# Generated by Django 2.1.2 on 2018-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IM', 'Imagem'), ('VI', 'Vídeo')], default='IM', max_length=2)),
                ('hashId', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.TextField(verbose_name='Nome da Localidade')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Latitute')),
                ('lng', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Longitude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
