# Generated by Django 2.1.2 on 2018-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0002_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='finishDate',
            field=models.DateField(blank=True, help_text='Esta informação só deve ser inserida caso não haja uma data precisa', null=True, verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='preciseDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data precisa'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='startDate',
            field=models.DateField(blank=True, help_text='Esta informação só deve ser inserida caso não haja uma data precisa', null=True, verbose_name='Data de início'),
        ),
    ]
