# Generated by Django 2.1.2 on 2018-10-09 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0003_auto_20181009_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrence.Location', verbose_name='Localização'),
        ),
    ]
