# Generated by Django 2.1.2 on 2018-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0005_auto_20181009_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='manifestations',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Atos e Manifestações'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='report',
            field=models.URLField(blank=True, null=True, verbose_name='URL da reportagem'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='stories',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Fichas narrativas'),
        ),
    ]
